  - name: Checkout code
    uses: actions/checkout@v3

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: '3.12'

  - name: Cache pip packages
    uses: actions/cache@v3
    with:
      path: ~/.cache/pip
      key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-pip-

  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install -r dev-requirements.txt
      pip install pytest coverage allure-pytest

  - name: Set PYTHONPATH
    run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

  - name: Run pytest & generate Allure results
    run: pytest --alluredir=allure-results

  - name: Run tests with coverage
    run: |
      # Run tests with coverage collecting info and generate XML report
      coverage run -m pytest --alluredir=allure-results
      coverage report -m
      coverage xml

  - name: Extract Coverage Percentage
    id: coverage
    run: |
      # Extract the TOTAL coverage percentage from the coverage report output
      COVERAGE=$(coverage report | awk '/TOTAL/ {gsub("%", "", $4); print $4}')
      echo "coverage=$COVERAGE" >> $GITHUB_OUTPUT

  - name: Post Coverage Comment on PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: marocchino/sticky-pull-request-comment@v2
    with:
      message: |
        ### Code Coverage Report
        ![Coverage Badge](https://img.shields.io/badge/Coverage-${{ steps.coverage.outputs.coverage }}%25-brightgreen)
        Detailed report available in [coverage.xml](./coverage.xml).

  - name: Generate Allure Report
    run: allure generate allure-results --clean -o allure-report

  - name: Deploy Allure Report to GitHub Pages
    uses: peaceiris/actions-gh-pages@v3
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_branch: gh-pages
      publish_dir: ./allure-report