name: Allure Report Workflow

on:
  workflow_dispatch:

jobs:
  run-tests-and-publish-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-venv-

    - name: Create and activate virtual environment
      run: |
        python -m venv .venv
        . .venv/bin/activate
        # Install dependencies only if not cached
        if [ ! -d ".venv" ]; then
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
        fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

    - name: Install Allure CLI
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.21.0/allure-2.21.0.tgz
        tar -xzf allure-2.21.0.tgz
        sudo mv allure-2.21.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure

    - name: Run tests and generate allure-results
      run: |
        . .venv/bin/activate && pytest --alluredir=allure-results

    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs